{
 "title": "System_Monitor",
 "description": "By Ghislain LE MEUR/Devansh",
 "tags": [
  "telegraf",
  "influxdb",
  "host",
  "system"
 ],
 "time": { "from": "now-24h", "to": "now-60s" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "host",
    "label": "host",
    "query": "SHOW TAG VALUES FROM \"system\" WITH KEY = \"host\""
   },
   {
    "name": "cpu",
    "label": "cpu",
    "query": "SHOW TAG VALUES FROM \"cpu\" WITH KEY = \"cpu\""
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "SHOW TAG VALUES FROM \"network\" WITH KEY = \"device\""
   },
   {
    "name": "disk",
    "label": "disk",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  { "title": "SUMMARY", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "select last(uptime_format) from system where  host =~ /^$host$/",
     "select": [
      [
       { "params": [ "uptime_format" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "mem",
     "query": "SELECT last(used_percent) FROM \"mem\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidiasmi",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *100/ 12188" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Fan",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" }
     ],
     "measurement": "nvidiasmi",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "/sdata Disk used (max)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ssd",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "/ldata Disk used (max)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "disk",
     "query": "SELECT max(used_percent) FROM \"disk\" WHERE \"host\" =~ /^$host$/ and \"device\" != 'rootfs'  and $timeFilter",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "greenburst" },
      { "condition": "AND", "key": "device", "operator": "=", "value": "sda1" }
     ]
    }
   ]
  },
  {
   "title": "load 1",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"load1\") FROM \"system\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "load 5",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"load1\") FROM \"system\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "load 15",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "system",
     "query": "SELECT last(\"load15\") FROM \"system\" WHERE \"host\" =~ /^$host$/",
     "select": [
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "GPU Fan",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Fan Speed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidiasmi",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidiasmi",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100/12188" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidiasmi",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "P state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "state",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "nvidiasmi",
     "select": [
      [
       { "params": [ "pstate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "load1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load1" ], "type": "alias" }
      ],
      [
       { "params": [ "load5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load5" ], "type": "alias" }
      ],
      [
       { "params": [ "load15" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "load15" ], "type": "alias" }
      ],
      [
       { "params": [ "n_cpus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cpu count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU used per CPUs ($cpu)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_cpu",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cpu" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT 100 - mean(\"usage_idle\") FROM \"cpu\" WHERE (\"cpu\" =~ /^$cpu$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval), \"cpu\" fill(null)",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "-100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "cpu", "operator": "=~", "value": "/^$cpu$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "processes",
     "query": "select blocked,running,sleeping,total,total_threads,zombies from processes where  host =~ /^$host$/ and $timeFilter",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "blocked" ], "type": "alias" }
      ],
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "running" ], "type": "alias" }
      ],
      [
       { "params": [ "sleeping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "sleeping" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "zombies" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "zombies" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Memory / Swap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used_percent",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT mean(\"used_percent\") FROM \"mem\" WHERE (\"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval) fill(null) ",
     "select": [
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ],
      [
       { "params": [ "cached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "cache" ], "type": "alias" }
      ],
      [
       { "params": [ "buffered" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "buffer" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Swap used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "% swap" ], "type": "alias" }
      ],
      [
       { "params": [ "used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used" ], "type": "alias" }
      ],
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "IO swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "swap",
     "select": [
      [
       { "params": [ "in" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "out" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Disk used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path ($tag_fstype on $tag_device)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE \"host\" =~ /^$host$/ and $timeFilter GROUP BY time($interval), \"path\" fill(null)",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "used_percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "/sdata",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ssd",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk inode used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_path ($tag_fstype on $tag_device)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" },
      { "params": [ "fstype" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "query": "SELECT mean(\"inodes_used\") / inodes_total FROM \"disk\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "/ mean(inodes_total)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO/s ($disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk throughput ($disk)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_name $col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT mean(\"rkB_per_s\") AS \"read\", mean(\"wkB_per_s\") AS \"write\" FROM \"disk\" WHERE (\"device\" =~ /^$disk$/ AND \"host\" =~ /^$host$/) AND $timeFilter GROUP BY time($interval), \"device\" fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$disk$/" }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "udp rcv buffer error",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "udp_rcvbuferrors" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bytes Rcv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "decgbytes", "label": "Rx" }
   ]
  },
  {
   "title": "Netstat",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "udp_indatagrams" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface", "operator": "=", "value": "all" }
     ]
    }
   ]
  }
 ]
}